api_platform:
  title: "La Course API"
  description: "L'API du site de La Course"
  version: "1.0.0"
  formats:
      json: ["application/json"]
      jsonld: ["application/ld+json"]
      html: ["text/html"]
      multipart: ["multipart/form-data"]
  patch_formats:
      json: ["application/merge-patch+json"]
  swagger:
    versions: [3]
    api_keys:
      token:
        name: Authorization
        type: header
