#controllers:
#    resource: ../src/Controller/
#    type: attribute
login:
    path: /login
    methods: ['POST']
privacy:
    path: /privacy-policy
    methods: ['GET']
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: 'privacy.html.twig'
